wandb_version: 1

learning_rate:
  desc: null
  value: 0.01
architecture:
  desc: null
  value: ResNet18
dataset:
  desc: null
  value: CIFAR10
epochs:
  desc: null
  value: 200
optimizer:
  desc: null
  value: SGD
loss_fn:
  desc: null
  value: CrossEntropyLoss
_wandb:
  desc: null
  value:
    python_version: 3.10.2
    cli_version: 0.15.0
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1682187059.256153
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 16
      - 23
      4: 3.10.2
      5: 0.15.0
      8:
      - 5
